FROM php:7.4.2

RUN apt-get update && apt-get install -y git libzip-dev zip unzip

RUN docker-php-ext-install pdo_mysql

RUN pecl install zip && docker-php-ext-enable zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN useradd -ms /bin/bash docker

USER docker

WORKDIR /var/www/html
