version: '3.7'

services:
  crypto-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-php
    volumes:
      - .:/var/www/html:cached
    networks:
      - crypto-net
    tty: true

  crypto-php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-php-fpm
    volumes:
      - .:/var/www/html:cached
    networks:
      - crypto-net
    tty: true

  crypto-nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
    depends_on:
      - crypto-php-fpm
    networks:
      - crypto-net

  crypto-mysql:
    image: mysql:8.0
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
    networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge
    name: 'crypto-net'
