api_main:
  path: /
  controller: App\Controller\AssetController::index
  methods: GET

api_list_assets:
  path: /assets
  controller: App\Controller\AssetController::list
  methods: GET

api_create_asset:
  path: /assets
  controller: App\Controller\AssetController::create
  methods: POST

api_get_asset:
  path: /assets/{uid}
  controller: App\Controller\AssetController::getOne
  methods: GET

api_update_asset:
  path: /assets/{uid}
  controller: App\Controller\AssetController::update
  methods: PUT

api_delete_asset:
  path: /assets/{uid}
  controller: App\Controller\AssetController::delete
  methods: DELETE
